### PR TITLE
UPDATE ticketutil methods with improved return statements

### PR DESCRIPTION
**Pull request by dmranck**
- ticketutil methods now return valuable information. A named tuple is
returned with status, url, and error_message fields for the main
ticketing operation methods.

### CODE REVIEW

**Comment by dmranck** [comment]
Using named tuples to return information from the user-accessible methods in redmine. 

(Review ticket.py before redmine.py to see where the default namedtuple is being created.)

**Comment by dmranck** [comment]
@Akasurde , if you could take a look at the latest commit (UPDATE ticketutil.jira methods with improved return statements) and let me know what you think, I'd really appreciate it.

**Comment by dmranck** [comment]
Rebased PR to incorporate recent commits adding HTTP Basic Auth support to JIRA and RT.

**Comment by dmranck** [comment]
Added a new commit to the PR for Bugzilla:

https://github.com/dmranck/ticketutil/pull/24/commits/2653b9c6356255dd79f73ad0efc31ac6fc74dd8d

@K-Gazdikova & @vashirov, if you could take a look, that'd be great. Documentation will be updated once I've finished the return-statements changes for all tools, but a quick summary:

`response = t.add_comment('Test comment')`

After running the above code, you could view the following response data:
**response.status** (Success or Failure)
**response.error_message** (Error message if response.status is Failure)
**response.url** (URL of the ticket you're working with)

**Comment by vashirov** [comment]
Is it possible in case of successful operation of adding comment or attachment return anchored url pointing to this comment or attachment?
Other than that, LGTM. Thanks!

**Comment by dmranck** [comment]
@pzubaty, @rpavelka, If you guys have time, I'd appreciate a review of the latest commit in this PR:
https://github.com/dmranck/ticketutil/pull/24/commits/3e9e71eb50b9802964a24bcd823cc559ab578e99
This PR involves adding useful return statements to all user-accessible methods in ticketutil. See my comments above for some additional information.

Note: I'll need to rework the servicenow unit tests and also edit documentation for all ticketutil tools before merging this.

**Comment by rpavelka** [comment]
Improved logging is definitely good. Is the documentation updated?

**Comment by dmranck** [comment]
No updated documentation yet - but I'll be updating it before merging this PR. It's next on my To-Do list (along with updating Pavel's unit tests as a result of the new return statements for each method).

**Comment by dmranck** [comment]
Updated SN unit tests and README documentation. Will plan to merge this by the end of the month.

**Comment by pzubaty** [comment]
Looks good to me.

**Comment by K-Gazdikova** [comment]
Hi Danny, 
As per our chat conversation adding the below modification requests,
1) Update readthedocs config file to refer our master branch for readthedocs branch.
2) Update  index.html file at the top (the code example) with the ticket and t changes.
3)  Add the return statements section under Usage file.

**Comment by K-Gazdikova** [comment]
Everything looks good to me 👍

**Pull request merged**
