### PR TITLE
Allow trailing slash on Jira URL

### PR DESCRIPTION
**Pull request by ddelabru**
Fixes issue #67

### CODE REVIEW

**Comment by ddelabru** [comment]
@dmranck, let me know what you think.

**Comment by dmranck** [comment]
Thanks for submitting this, @ddelabru! What about something a little bit simpler, which would remove the new explicit six dependency and prevent you from having to alter the urls throughout the code. Maybe change line 21 from:

`self.url = url`

to something like:

`self.url = url[:-1] if url.endswith('/') else url`

If you like this approach, could you also make the same change in rt.py, servicenow.py, redmine.py, and bugzilla.py? Let me know what you think. Thanks again!

**Comment by ddelabru** [comment]
Ah, yeah, I can see how the simpler / more explicit / less library-dependent approach fits better for ticketutil. I'll go do something like that for all 5 of the ticket services.

**Comment by ddelabru** [comment]
I have made the suggested change.

**Pull request merged**
